# Generated by Django 5.2.6 on 2025-09-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ouflow',
            new_name='Outflow',
        ),
    ]
